[features]
seeds = false
skip-lint = false
[programs.devnet]
starter = "C5iFhc6tLPSmG2bck6C36DMDLMXDscQXCEhwJArvZAMJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
