[features]
seeds = false
skip-lint = false
[programs.localnet]
flipper = "bXHdKxE4Ti8gsQUSSWvhodPpgjcQFHtdnYx2Ab1S2S2"
cpi = "JCEZ3WFA6jCP35ywaLZaqn8dSs1p3JQXJFqKwGJffCVZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
