[features]
seeds = false
skip-lint = false

[programs.localnet]
cpi = "6BLnqBHgaShKoMMZRKxoPfG4oBrUQD7gbAgikZbpo7Nx"
flipper = "GyWjf3mHhKi5Qbr57crXzannY9JDrF3x5U4FSx8z8urh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
